version: 2
project_name: config-server
builds:
  - id: config-server
    binary: config-server
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - config-server
    image_templates:
      - "ghcr.io/sdcio/config-server:v0.0.0-{{ if index .Env \"PR\"  }}PR{{ .Env.PR }}-{{ .ShortCommit }}{{ else }}{{ .ShortCommit }}{{ end }}"
    dockerfile: goreleaser.dockerfile
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--build-arg=USERID=10000"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/sdcio/{{.ProjectName}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
release:
  disable: true
