version: 2
project_name: config-server
builds:
  - id: api-server
    binary:  api-server
    main: ./cmd/api-server/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: controller
    binary: controller
    main: ./cmd/controller/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - id: api-server-docker
    goos: linux
    goarch: amd64
    ids:
      - api-server
    image_templates:
      - "ghcr.io/sdcio/{{ .ProjectName }}-api-server:v0.0.0-{{ if index .Env \"PR\"  }}PR{{ .Env.PR }}-{{ .ShortCommit }}{{ else }}{{ .ShortCommit }}{{ end }}"
    dockerfile: goreleaser.api-server.dockerfile
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--build-arg=USERID=10000"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}-api-server"
      - "--label=org.opencontainers.image.source=https://github.com/sdcio/{{.ProjectName}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
  - id: controller-docker
    goos: linux
    goarch: amd64
    ids:
      - controller
    image_templates:
      - "ghcr.io/sdcio/{{ .ProjectName }}-controller:v0.0.0-{{ if index .Env \"PR\"  }}PR{{ .Env.PR }}-{{ .ShortCommit }}{{ else }}{{ .ShortCommit }}{{ end }}"
    dockerfile: goreleaser.controller.dockerfile
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--build-arg=USERID=10000"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}-controller"
      - "--label=org.opencontainers.image.source=https://github.com/sdcio/{{.ProjectName}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
release:
  disable: true
