//go:build kubernetes_protomessage_one_more_release
// +build kubernetes_protomessage_one_more_release

/*
Copyright 2024 Nokia.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by go-to-protobuf. DO NOT EDIT.

package v1alpha1

func (*DiscoveryParameters) ProtoMessage() {}

func (*DiscoveryPathDefinition) ProtoMessage() {}

func (*DiscoveryProfile) ProtoMessage() {}

func (*DiscoveryRule) ProtoMessage() {}

func (*DiscoveryRuleAddress) ProtoMessage() {}

func (*DiscoveryRuleList) ProtoMessage() {}

func (*DiscoveryRulePrefix) ProtoMessage() {}

func (*DiscoveryRuleSpec) ProtoMessage() {}

func (*DiscoveryRuleStatus) ProtoMessage() {}

func (*DiscoveryVendorProfile) ProtoMessage() {}

func (*DiscoveryVendorProfileList) ProtoMessage() {}

func (*DiscoveryVendorProfileSpec) ProtoMessage() {}

func (*GnmiDiscoveryVendorProfileParameters) ProtoMessage() {}

func (*Proxy) ProtoMessage() {}

func (*Repository) ProtoMessage() {}

func (*Rollout) ProtoMessage() {}

func (*RolloutList) ProtoMessage() {}

func (*RolloutSpec) ProtoMessage() {}

func (*RolloutStatus) ProtoMessage() {}

func (*RolloutTargetStatus) ProtoMessage() {}

func (*Schema) ProtoMessage() {}

func (*SchemaKey) ProtoMessage() {}

func (*SchemaList) ProtoMessage() {}

func (*SchemaRepositoryStatus) ProtoMessage() {}

func (*SchemaSpec) ProtoMessage() {}

func (*SchemaSpecRepository) ProtoMessage() {}

func (*SchemaSpecSchema) ProtoMessage() {}

func (*SchemaStatus) ProtoMessage() {}

func (*SrcDstPath) ProtoMessage() {}

func (*Subscription) ProtoMessage() {}

func (*SubscriptionList) ProtoMessage() {}

func (*SubscriptionParameters) ProtoMessage() {}

func (*SubscriptionSpec) ProtoMessage() {}

func (*SubscriptionStatus) ProtoMessage() {}

func (*SubscriptionTarget) ProtoMessage() {}

func (*TargetConnectionProfile) ProtoMessage() {}

func (*TargetConnectionProfileList) ProtoMessage() {}

func (*TargetConnectionProfileSpec) ProtoMessage() {}

func (*TargetProfile) ProtoMessage() {}

func (*TargetSyncProfile) ProtoMessage() {}

func (*TargetSyncProfileList) ProtoMessage() {}

func (*TargetSyncProfileSpec) ProtoMessage() {}

func (*TargetSyncProfileSync) ProtoMessage() {}

func (*TargetTemplate) ProtoMessage() {}

func (*Workspace) ProtoMessage() {}

func (*WorkspaceList) ProtoMessage() {}

func (*WorkspaceSpec) ProtoMessage() {}

func (*WorkspaceStatus) ProtoMessage() {}
