//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 Nokia.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	condition "github.com/sdcio/config-server/apis/condition"
	conditionv1alpha1 "github.com/sdcio/config-server/apis/condition/v1alpha1"
	config "github.com/sdcio/config-server/apis/config"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Config)(nil), (*config.Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Config_To_config_Config(a.(*Config), b.(*config.Config), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Config)(nil), (*Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Config_To_v1alpha1_Config(a.(*config.Config), b.(*Config), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigBlame)(nil), (*config.ConfigBlame)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigBlame_To_config_ConfigBlame(a.(*ConfigBlame), b.(*config.ConfigBlame), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigBlame)(nil), (*ConfigBlame)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigBlame_To_v1alpha1_ConfigBlame(a.(*config.ConfigBlame), b.(*ConfigBlame), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigBlameList)(nil), (*config.ConfigBlameList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigBlameList_To_config_ConfigBlameList(a.(*ConfigBlameList), b.(*config.ConfigBlameList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigBlameList)(nil), (*ConfigBlameList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigBlameList_To_v1alpha1_ConfigBlameList(a.(*config.ConfigBlameList), b.(*ConfigBlameList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigBlameSpec)(nil), (*config.ConfigBlameSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigBlameSpec_To_config_ConfigBlameSpec(a.(*ConfigBlameSpec), b.(*config.ConfigBlameSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigBlameSpec)(nil), (*ConfigBlameSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigBlameSpec_To_v1alpha1_ConfigBlameSpec(a.(*config.ConfigBlameSpec), b.(*ConfigBlameSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigBlameStatus)(nil), (*config.ConfigBlameStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigBlameStatus_To_config_ConfigBlameStatus(a.(*ConfigBlameStatus), b.(*config.ConfigBlameStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigBlameStatus)(nil), (*ConfigBlameStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigBlameStatus_To_v1alpha1_ConfigBlameStatus(a.(*config.ConfigBlameStatus), b.(*ConfigBlameStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigBlob)(nil), (*config.ConfigBlob)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigBlob_To_config_ConfigBlob(a.(*ConfigBlob), b.(*config.ConfigBlob), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigBlob)(nil), (*ConfigBlob)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigBlob_To_v1alpha1_ConfigBlob(a.(*config.ConfigBlob), b.(*ConfigBlob), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigDeviation)(nil), (*config.ConfigDeviation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigDeviation_To_config_ConfigDeviation(a.(*ConfigDeviation), b.(*config.ConfigDeviation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigDeviation)(nil), (*ConfigDeviation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigDeviation_To_v1alpha1_ConfigDeviation(a.(*config.ConfigDeviation), b.(*ConfigDeviation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigList)(nil), (*config.ConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigList_To_config_ConfigList(a.(*ConfigList), b.(*config.ConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigList)(nil), (*ConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigList_To_v1alpha1_ConfigList(a.(*config.ConfigList), b.(*ConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigSet)(nil), (*config.ConfigSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigSet_To_config_ConfigSet(a.(*ConfigSet), b.(*config.ConfigSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigSet)(nil), (*ConfigSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigSet_To_v1alpha1_ConfigSet(a.(*config.ConfigSet), b.(*ConfigSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigSetList)(nil), (*config.ConfigSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigSetList_To_config_ConfigSetList(a.(*ConfigSetList), b.(*config.ConfigSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigSetList)(nil), (*ConfigSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigSetList_To_v1alpha1_ConfigSetList(a.(*config.ConfigSetList), b.(*ConfigSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigSetSpec)(nil), (*config.ConfigSetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigSetSpec_To_config_ConfigSetSpec(a.(*ConfigSetSpec), b.(*config.ConfigSetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigSetSpec)(nil), (*ConfigSetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigSetSpec_To_v1alpha1_ConfigSetSpec(a.(*config.ConfigSetSpec), b.(*ConfigSetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigSetStatus)(nil), (*config.ConfigSetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigSetStatus_To_config_ConfigSetStatus(a.(*ConfigSetStatus), b.(*config.ConfigSetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigSetStatus)(nil), (*ConfigSetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigSetStatus_To_v1alpha1_ConfigSetStatus(a.(*config.ConfigSetStatus), b.(*ConfigSetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigSetTarget)(nil), (*config.ConfigSetTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigSetTarget_To_config_ConfigSetTarget(a.(*ConfigSetTarget), b.(*config.ConfigSetTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigSetTarget)(nil), (*ConfigSetTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigSetTarget_To_v1alpha1_ConfigSetTarget(a.(*config.ConfigSetTarget), b.(*ConfigSetTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigSetTargetStatus)(nil), (*config.ConfigSetTargetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigSetTargetStatus_To_config_ConfigSetTargetStatus(a.(*ConfigSetTargetStatus), b.(*config.ConfigSetTargetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigSetTargetStatus)(nil), (*ConfigSetTargetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigSetTargetStatus_To_v1alpha1_ConfigSetTargetStatus(a.(*config.ConfigSetTargetStatus), b.(*ConfigSetTargetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigSpec)(nil), (*config.ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigSpec_To_config_ConfigSpec(a.(*ConfigSpec), b.(*config.ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigSpec)(nil), (*ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigSpec_To_v1alpha1_ConfigSpec(a.(*config.ConfigSpec), b.(*ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigStatus)(nil), (*config.ConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigStatus_To_config_ConfigStatus(a.(*ConfigStatus), b.(*config.ConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigStatus)(nil), (*ConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigStatus_To_v1alpha1_ConfigStatus(a.(*config.ConfigStatus), b.(*ConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigStatusLastKnownGoodSchema)(nil), (*config.ConfigStatusLastKnownGoodSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigStatusLastKnownGoodSchema_To_config_ConfigStatusLastKnownGoodSchema(a.(*ConfigStatusLastKnownGoodSchema), b.(*config.ConfigStatusLastKnownGoodSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigStatusLastKnownGoodSchema)(nil), (*ConfigStatusLastKnownGoodSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigStatusLastKnownGoodSchema_To_v1alpha1_ConfigStatusLastKnownGoodSchema(a.(*config.ConfigStatusLastKnownGoodSchema), b.(*ConfigStatusLastKnownGoodSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Deviation)(nil), (*config.Deviation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Deviation_To_config_Deviation(a.(*Deviation), b.(*config.Deviation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Deviation)(nil), (*Deviation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Deviation_To_v1alpha1_Deviation(a.(*config.Deviation), b.(*Deviation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeviationList)(nil), (*config.DeviationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviationList_To_config_DeviationList(a.(*DeviationList), b.(*config.DeviationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DeviationList)(nil), (*DeviationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DeviationList_To_v1alpha1_DeviationList(a.(*config.DeviationList), b.(*DeviationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeviationSpec)(nil), (*config.DeviationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviationSpec_To_config_DeviationSpec(a.(*DeviationSpec), b.(*config.DeviationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DeviationSpec)(nil), (*DeviationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DeviationSpec_To_v1alpha1_DeviationSpec(a.(*config.DeviationSpec), b.(*DeviationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeviationStatus)(nil), (*config.DeviationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviationStatus_To_config_DeviationStatus(a.(*DeviationStatus), b.(*config.DeviationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DeviationStatus)(nil), (*DeviationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DeviationStatus_To_v1alpha1_DeviationStatus(a.(*config.DeviationStatus), b.(*DeviationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiscoveryInfo)(nil), (*config.DiscoveryInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiscoveryInfo_To_config_DiscoveryInfo(a.(*DiscoveryInfo), b.(*config.DiscoveryInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DiscoveryInfo)(nil), (*DiscoveryInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DiscoveryInfo_To_v1alpha1_DiscoveryInfo(a.(*config.DiscoveryInfo), b.(*DiscoveryInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Lifecycle)(nil), (*config.Lifecycle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Lifecycle_To_config_Lifecycle(a.(*Lifecycle), b.(*config.Lifecycle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Lifecycle)(nil), (*Lifecycle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Lifecycle_To_v1alpha1_Lifecycle(a.(*config.Lifecycle), b.(*Lifecycle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RunningConfig)(nil), (*config.RunningConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RunningConfig_To_config_RunningConfig(a.(*RunningConfig), b.(*config.RunningConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RunningConfig)(nil), (*RunningConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RunningConfig_To_v1alpha1_RunningConfig(a.(*config.RunningConfig), b.(*RunningConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RunningConfigList)(nil), (*config.RunningConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RunningConfigList_To_config_RunningConfigList(a.(*RunningConfigList), b.(*config.RunningConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RunningConfigList)(nil), (*RunningConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RunningConfigList_To_v1alpha1_RunningConfigList(a.(*config.RunningConfigList), b.(*RunningConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RunningConfigSpec)(nil), (*config.RunningConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RunningConfigSpec_To_config_RunningConfigSpec(a.(*RunningConfigSpec), b.(*config.RunningConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RunningConfigSpec)(nil), (*RunningConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RunningConfigSpec_To_v1alpha1_RunningConfigSpec(a.(*config.RunningConfigSpec), b.(*RunningConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RunningConfigStatus)(nil), (*config.RunningConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RunningConfigStatus_To_config_RunningConfigStatus(a.(*RunningConfigStatus), b.(*config.RunningConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RunningConfigStatus)(nil), (*RunningConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RunningConfigStatus_To_v1alpha1_RunningConfigStatus(a.(*config.RunningConfigStatus), b.(*RunningConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SensitiveConfig)(nil), (*config.SensitiveConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SensitiveConfig_To_config_SensitiveConfig(a.(*SensitiveConfig), b.(*config.SensitiveConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SensitiveConfig)(nil), (*SensitiveConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SensitiveConfig_To_v1alpha1_SensitiveConfig(a.(*config.SensitiveConfig), b.(*SensitiveConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SensitiveConfigData)(nil), (*config.SensitiveConfigData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SensitiveConfigData_To_config_SensitiveConfigData(a.(*SensitiveConfigData), b.(*config.SensitiveConfigData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SensitiveConfigData)(nil), (*SensitiveConfigData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SensitiveConfigData_To_v1alpha1_SensitiveConfigData(a.(*config.SensitiveConfigData), b.(*SensitiveConfigData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SensitiveConfigList)(nil), (*config.SensitiveConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SensitiveConfigList_To_config_SensitiveConfigList(a.(*SensitiveConfigList), b.(*config.SensitiveConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SensitiveConfigList)(nil), (*SensitiveConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SensitiveConfigList_To_v1alpha1_SensitiveConfigList(a.(*config.SensitiveConfigList), b.(*SensitiveConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SensitiveConfigSpec)(nil), (*config.SensitiveConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SensitiveConfigSpec_To_config_SensitiveConfigSpec(a.(*SensitiveConfigSpec), b.(*config.SensitiveConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SensitiveConfigSpec)(nil), (*SensitiveConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SensitiveConfigSpec_To_v1alpha1_SensitiveConfigSpec(a.(*config.SensitiveConfigSpec), b.(*SensitiveConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SensitiveConfigStatus)(nil), (*config.SensitiveConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SensitiveConfigStatus_To_config_SensitiveConfigStatus(a.(*SensitiveConfigStatus), b.(*config.SensitiveConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SensitiveConfigStatus)(nil), (*SensitiveConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SensitiveConfigStatus_To_v1alpha1_SensitiveConfigStatus(a.(*config.SensitiveConfigStatus), b.(*SensitiveConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Target)(nil), (*config.Target)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Target_To_config_Target(a.(*Target), b.(*config.Target), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Target)(nil), (*Target)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Target_To_v1alpha1_Target(a.(*config.Target), b.(*Target), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TargetList)(nil), (*config.TargetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TargetList_To_config_TargetList(a.(*TargetList), b.(*config.TargetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TargetList)(nil), (*TargetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TargetList_To_v1alpha1_TargetList(a.(*config.TargetList), b.(*TargetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TargetSpec)(nil), (*config.TargetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TargetSpec_To_config_TargetSpec(a.(*TargetSpec), b.(*config.TargetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TargetSpec)(nil), (*TargetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TargetSpec_To_v1alpha1_TargetSpec(a.(*config.TargetSpec), b.(*TargetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TargetStatus)(nil), (*config.TargetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TargetStatus_To_config_TargetStatus(a.(*TargetStatus), b.(*config.TargetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TargetStatus)(nil), (*TargetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TargetStatus_To_v1alpha1_TargetStatus(a.(*config.TargetStatus), b.(*TargetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TargetStatusUsedReferences)(nil), (*config.TargetStatusUsedReferences)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TargetStatusUsedReferences_To_config_TargetStatusUsedReferences(a.(*TargetStatusUsedReferences), b.(*config.TargetStatusUsedReferences), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TargetStatusUsedReferences)(nil), (*TargetStatusUsedReferences)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TargetStatusUsedReferences_To_v1alpha1_TargetStatusUsedReferences(a.(*config.TargetStatusUsedReferences), b.(*TargetStatusUsedReferences), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*condition.Condition)(nil), (*conditionv1alpha1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_condition_Condition_To_v1alpha1_Condition(a.(*condition.Condition), b.(*conditionv1alpha1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*condition.ConditionedStatus)(nil), (*conditionv1alpha1.ConditionedStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_condition_ConditionedStatus_To_v1alpha1_ConditionedStatus(a.(*condition.ConditionedStatus), b.(*conditionv1alpha1.ConditionedStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*conditionv1alpha1.Condition)(nil), (*condition.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Condition_To_condition_Condition(a.(*conditionv1alpha1.Condition), b.(*condition.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*conditionv1alpha1.ConditionedStatus)(nil), (*condition.ConditionedStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConditionedStatus_To_condition_ConditionedStatus(a.(*conditionv1alpha1.ConditionedStatus), b.(*condition.ConditionedStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Config_To_config_Config(in *Config, out *config.Config, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ConfigSpec_To_config_ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ConfigStatus_To_config_ConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Config_To_config_Config is an autogenerated conversion function.
func Convert_v1alpha1_Config_To_config_Config(in *Config, out *config.Config, s conversion.Scope) error {
	return autoConvert_v1alpha1_Config_To_config_Config(in, out, s)
}

func autoConvert_config_Config_To_v1alpha1_Config(in *config.Config, out *Config, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_config_ConfigSpec_To_v1alpha1_ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_config_ConfigStatus_To_v1alpha1_ConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Config_To_v1alpha1_Config is an autogenerated conversion function.
func Convert_config_Config_To_v1alpha1_Config(in *config.Config, out *Config, s conversion.Scope) error {
	return autoConvert_config_Config_To_v1alpha1_Config(in, out, s)
}

func autoConvert_v1alpha1_ConfigBlame_To_config_ConfigBlame(in *ConfigBlame, out *config.ConfigBlame, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ConfigBlameSpec_To_config_ConfigBlameSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ConfigBlameStatus_To_config_ConfigBlameStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ConfigBlame_To_config_ConfigBlame is an autogenerated conversion function.
func Convert_v1alpha1_ConfigBlame_To_config_ConfigBlame(in *ConfigBlame, out *config.ConfigBlame, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigBlame_To_config_ConfigBlame(in, out, s)
}

func autoConvert_config_ConfigBlame_To_v1alpha1_ConfigBlame(in *config.ConfigBlame, out *ConfigBlame, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_config_ConfigBlameSpec_To_v1alpha1_ConfigBlameSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_config_ConfigBlameStatus_To_v1alpha1_ConfigBlameStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ConfigBlame_To_v1alpha1_ConfigBlame is an autogenerated conversion function.
func Convert_config_ConfigBlame_To_v1alpha1_ConfigBlame(in *config.ConfigBlame, out *ConfigBlame, s conversion.Scope) error {
	return autoConvert_config_ConfigBlame_To_v1alpha1_ConfigBlame(in, out, s)
}

func autoConvert_v1alpha1_ConfigBlameList_To_config_ConfigBlameList(in *ConfigBlameList, out *config.ConfigBlameList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]config.ConfigBlame)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ConfigBlameList_To_config_ConfigBlameList is an autogenerated conversion function.
func Convert_v1alpha1_ConfigBlameList_To_config_ConfigBlameList(in *ConfigBlameList, out *config.ConfigBlameList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigBlameList_To_config_ConfigBlameList(in, out, s)
}

func autoConvert_config_ConfigBlameList_To_v1alpha1_ConfigBlameList(in *config.ConfigBlameList, out *ConfigBlameList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ConfigBlame)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_config_ConfigBlameList_To_v1alpha1_ConfigBlameList is an autogenerated conversion function.
func Convert_config_ConfigBlameList_To_v1alpha1_ConfigBlameList(in *config.ConfigBlameList, out *ConfigBlameList, s conversion.Scope) error {
	return autoConvert_config_ConfigBlameList_To_v1alpha1_ConfigBlameList(in, out, s)
}

func autoConvert_v1alpha1_ConfigBlameSpec_To_config_ConfigBlameSpec(in *ConfigBlameSpec, out *config.ConfigBlameSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ConfigBlameSpec_To_config_ConfigBlameSpec is an autogenerated conversion function.
func Convert_v1alpha1_ConfigBlameSpec_To_config_ConfigBlameSpec(in *ConfigBlameSpec, out *config.ConfigBlameSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigBlameSpec_To_config_ConfigBlameSpec(in, out, s)
}

func autoConvert_config_ConfigBlameSpec_To_v1alpha1_ConfigBlameSpec(in *config.ConfigBlameSpec, out *ConfigBlameSpec, s conversion.Scope) error {
	return nil
}

// Convert_config_ConfigBlameSpec_To_v1alpha1_ConfigBlameSpec is an autogenerated conversion function.
func Convert_config_ConfigBlameSpec_To_v1alpha1_ConfigBlameSpec(in *config.ConfigBlameSpec, out *ConfigBlameSpec, s conversion.Scope) error {
	return autoConvert_config_ConfigBlameSpec_To_v1alpha1_ConfigBlameSpec(in, out, s)
}

func autoConvert_v1alpha1_ConfigBlameStatus_To_config_ConfigBlameStatus(in *ConfigBlameStatus, out *config.ConfigBlameStatus, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_ConfigBlameStatus_To_config_ConfigBlameStatus is an autogenerated conversion function.
func Convert_v1alpha1_ConfigBlameStatus_To_config_ConfigBlameStatus(in *ConfigBlameStatus, out *config.ConfigBlameStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigBlameStatus_To_config_ConfigBlameStatus(in, out, s)
}

func autoConvert_config_ConfigBlameStatus_To_v1alpha1_ConfigBlameStatus(in *config.ConfigBlameStatus, out *ConfigBlameStatus, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_config_ConfigBlameStatus_To_v1alpha1_ConfigBlameStatus is an autogenerated conversion function.
func Convert_config_ConfigBlameStatus_To_v1alpha1_ConfigBlameStatus(in *config.ConfigBlameStatus, out *ConfigBlameStatus, s conversion.Scope) error {
	return autoConvert_config_ConfigBlameStatus_To_v1alpha1_ConfigBlameStatus(in, out, s)
}

func autoConvert_v1alpha1_ConfigBlob_To_config_ConfigBlob(in *ConfigBlob, out *config.ConfigBlob, s conversion.Scope) error {
	out.Path = in.Path
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_ConfigBlob_To_config_ConfigBlob is an autogenerated conversion function.
func Convert_v1alpha1_ConfigBlob_To_config_ConfigBlob(in *ConfigBlob, out *config.ConfigBlob, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigBlob_To_config_ConfigBlob(in, out, s)
}

func autoConvert_config_ConfigBlob_To_v1alpha1_ConfigBlob(in *config.ConfigBlob, out *ConfigBlob, s conversion.Scope) error {
	out.Path = in.Path
	out.Value = in.Value
	return nil
}

// Convert_config_ConfigBlob_To_v1alpha1_ConfigBlob is an autogenerated conversion function.
func Convert_config_ConfigBlob_To_v1alpha1_ConfigBlob(in *config.ConfigBlob, out *ConfigBlob, s conversion.Scope) error {
	return autoConvert_config_ConfigBlob_To_v1alpha1_ConfigBlob(in, out, s)
}

func autoConvert_v1alpha1_ConfigDeviation_To_config_ConfigDeviation(in *ConfigDeviation, out *config.ConfigDeviation, s conversion.Scope) error {
	out.Path = in.Path
	out.DesiredValue = (*string)(unsafe.Pointer(in.DesiredValue))
	out.ActualValue = (*string)(unsafe.Pointer(in.ActualValue))
	out.Reason = in.Reason
	return nil
}

// Convert_v1alpha1_ConfigDeviation_To_config_ConfigDeviation is an autogenerated conversion function.
func Convert_v1alpha1_ConfigDeviation_To_config_ConfigDeviation(in *ConfigDeviation, out *config.ConfigDeviation, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigDeviation_To_config_ConfigDeviation(in, out, s)
}

func autoConvert_config_ConfigDeviation_To_v1alpha1_ConfigDeviation(in *config.ConfigDeviation, out *ConfigDeviation, s conversion.Scope) error {
	out.Path = in.Path
	out.DesiredValue = (*string)(unsafe.Pointer(in.DesiredValue))
	out.ActualValue = (*string)(unsafe.Pointer(in.ActualValue))
	out.Reason = in.Reason
	return nil
}

// Convert_config_ConfigDeviation_To_v1alpha1_ConfigDeviation is an autogenerated conversion function.
func Convert_config_ConfigDeviation_To_v1alpha1_ConfigDeviation(in *config.ConfigDeviation, out *ConfigDeviation, s conversion.Scope) error {
	return autoConvert_config_ConfigDeviation_To_v1alpha1_ConfigDeviation(in, out, s)
}

func autoConvert_v1alpha1_ConfigList_To_config_ConfigList(in *ConfigList, out *config.ConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]config.Config, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Config_To_config_Config(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ConfigList_To_config_ConfigList is an autogenerated conversion function.
func Convert_v1alpha1_ConfigList_To_config_ConfigList(in *ConfigList, out *config.ConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigList_To_config_ConfigList(in, out, s)
}

func autoConvert_config_ConfigList_To_v1alpha1_ConfigList(in *config.ConfigList, out *ConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Config, len(*in))
		for i := range *in {
			if err := Convert_config_Config_To_v1alpha1_Config(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_config_ConfigList_To_v1alpha1_ConfigList is an autogenerated conversion function.
func Convert_config_ConfigList_To_v1alpha1_ConfigList(in *config.ConfigList, out *ConfigList, s conversion.Scope) error {
	return autoConvert_config_ConfigList_To_v1alpha1_ConfigList(in, out, s)
}

func autoConvert_v1alpha1_ConfigSet_To_config_ConfigSet(in *ConfigSet, out *config.ConfigSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ConfigSetSpec_To_config_ConfigSetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ConfigSetStatus_To_config_ConfigSetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ConfigSet_To_config_ConfigSet is an autogenerated conversion function.
func Convert_v1alpha1_ConfigSet_To_config_ConfigSet(in *ConfigSet, out *config.ConfigSet, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigSet_To_config_ConfigSet(in, out, s)
}

func autoConvert_config_ConfigSet_To_v1alpha1_ConfigSet(in *config.ConfigSet, out *ConfigSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_config_ConfigSetSpec_To_v1alpha1_ConfigSetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_config_ConfigSetStatus_To_v1alpha1_ConfigSetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ConfigSet_To_v1alpha1_ConfigSet is an autogenerated conversion function.
func Convert_config_ConfigSet_To_v1alpha1_ConfigSet(in *config.ConfigSet, out *ConfigSet, s conversion.Scope) error {
	return autoConvert_config_ConfigSet_To_v1alpha1_ConfigSet(in, out, s)
}

func autoConvert_v1alpha1_ConfigSetList_To_config_ConfigSetList(in *ConfigSetList, out *config.ConfigSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]config.ConfigSet, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ConfigSet_To_config_ConfigSet(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ConfigSetList_To_config_ConfigSetList is an autogenerated conversion function.
func Convert_v1alpha1_ConfigSetList_To_config_ConfigSetList(in *ConfigSetList, out *config.ConfigSetList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigSetList_To_config_ConfigSetList(in, out, s)
}

func autoConvert_config_ConfigSetList_To_v1alpha1_ConfigSetList(in *config.ConfigSetList, out *ConfigSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigSet, len(*in))
		for i := range *in {
			if err := Convert_config_ConfigSet_To_v1alpha1_ConfigSet(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_config_ConfigSetList_To_v1alpha1_ConfigSetList is an autogenerated conversion function.
func Convert_config_ConfigSetList_To_v1alpha1_ConfigSetList(in *config.ConfigSetList, out *ConfigSetList, s conversion.Scope) error {
	return autoConvert_config_ConfigSetList_To_v1alpha1_ConfigSetList(in, out, s)
}

func autoConvert_v1alpha1_ConfigSetSpec_To_config_ConfigSetSpec(in *ConfigSetSpec, out *config.ConfigSetSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ConfigSetTarget_To_config_ConfigSetTarget(&in.Target, &out.Target, s); err != nil {
		return err
	}
	out.Lifecycle = (*config.Lifecycle)(unsafe.Pointer(in.Lifecycle))
	out.Priority = in.Priority
	out.Revertive = (*bool)(unsafe.Pointer(in.Revertive))
	out.Config = *(*[]config.ConfigBlob)(unsafe.Pointer(&in.Config))
	return nil
}

// Convert_v1alpha1_ConfigSetSpec_To_config_ConfigSetSpec is an autogenerated conversion function.
func Convert_v1alpha1_ConfigSetSpec_To_config_ConfigSetSpec(in *ConfigSetSpec, out *config.ConfigSetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigSetSpec_To_config_ConfigSetSpec(in, out, s)
}

func autoConvert_config_ConfigSetSpec_To_v1alpha1_ConfigSetSpec(in *config.ConfigSetSpec, out *ConfigSetSpec, s conversion.Scope) error {
	if err := Convert_config_ConfigSetTarget_To_v1alpha1_ConfigSetTarget(&in.Target, &out.Target, s); err != nil {
		return err
	}
	out.Lifecycle = (*Lifecycle)(unsafe.Pointer(in.Lifecycle))
	out.Priority = in.Priority
	out.Revertive = (*bool)(unsafe.Pointer(in.Revertive))
	out.Config = *(*[]ConfigBlob)(unsafe.Pointer(&in.Config))
	return nil
}

// Convert_config_ConfigSetSpec_To_v1alpha1_ConfigSetSpec is an autogenerated conversion function.
func Convert_config_ConfigSetSpec_To_v1alpha1_ConfigSetSpec(in *config.ConfigSetSpec, out *ConfigSetSpec, s conversion.Scope) error {
	return autoConvert_config_ConfigSetSpec_To_v1alpha1_ConfigSetSpec(in, out, s)
}

func autoConvert_v1alpha1_ConfigSetStatus_To_config_ConfigSetStatus(in *ConfigSetStatus, out *config.ConfigSetStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ConditionedStatus_To_condition_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]config.ConfigSetTargetStatus, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ConfigSetTargetStatus_To_config_ConfigSetTargetStatus(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Targets = nil
	}
	return nil
}

// Convert_v1alpha1_ConfigSetStatus_To_config_ConfigSetStatus is an autogenerated conversion function.
func Convert_v1alpha1_ConfigSetStatus_To_config_ConfigSetStatus(in *ConfigSetStatus, out *config.ConfigSetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigSetStatus_To_config_ConfigSetStatus(in, out, s)
}

func autoConvert_config_ConfigSetStatus_To_v1alpha1_ConfigSetStatus(in *config.ConfigSetStatus, out *ConfigSetStatus, s conversion.Scope) error {
	if err := Convert_condition_ConditionedStatus_To_v1alpha1_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]ConfigSetTargetStatus, len(*in))
		for i := range *in {
			if err := Convert_config_ConfigSetTargetStatus_To_v1alpha1_ConfigSetTargetStatus(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Targets = nil
	}
	return nil
}

// Convert_config_ConfigSetStatus_To_v1alpha1_ConfigSetStatus is an autogenerated conversion function.
func Convert_config_ConfigSetStatus_To_v1alpha1_ConfigSetStatus(in *config.ConfigSetStatus, out *ConfigSetStatus, s conversion.Scope) error {
	return autoConvert_config_ConfigSetStatus_To_v1alpha1_ConfigSetStatus(in, out, s)
}

func autoConvert_v1alpha1_ConfigSetTarget_To_config_ConfigSetTarget(in *ConfigSetTarget, out *config.ConfigSetTarget, s conversion.Scope) error {
	out.TargetSelector = (*v1.LabelSelector)(unsafe.Pointer(in.TargetSelector))
	return nil
}

// Convert_v1alpha1_ConfigSetTarget_To_config_ConfigSetTarget is an autogenerated conversion function.
func Convert_v1alpha1_ConfigSetTarget_To_config_ConfigSetTarget(in *ConfigSetTarget, out *config.ConfigSetTarget, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigSetTarget_To_config_ConfigSetTarget(in, out, s)
}

func autoConvert_config_ConfigSetTarget_To_v1alpha1_ConfigSetTarget(in *config.ConfigSetTarget, out *ConfigSetTarget, s conversion.Scope) error {
	out.TargetSelector = (*v1.LabelSelector)(unsafe.Pointer(in.TargetSelector))
	return nil
}

// Convert_config_ConfigSetTarget_To_v1alpha1_ConfigSetTarget is an autogenerated conversion function.
func Convert_config_ConfigSetTarget_To_v1alpha1_ConfigSetTarget(in *config.ConfigSetTarget, out *ConfigSetTarget, s conversion.Scope) error {
	return autoConvert_config_ConfigSetTarget_To_v1alpha1_ConfigSetTarget(in, out, s)
}

func autoConvert_v1alpha1_ConfigSetTargetStatus_To_config_ConfigSetTargetStatus(in *ConfigSetTargetStatus, out *config.ConfigSetTargetStatus, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_Condition_To_condition_Condition(&in.Condition, &out.Condition, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ConfigSetTargetStatus_To_config_ConfigSetTargetStatus is an autogenerated conversion function.
func Convert_v1alpha1_ConfigSetTargetStatus_To_config_ConfigSetTargetStatus(in *ConfigSetTargetStatus, out *config.ConfigSetTargetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigSetTargetStatus_To_config_ConfigSetTargetStatus(in, out, s)
}

func autoConvert_config_ConfigSetTargetStatus_To_v1alpha1_ConfigSetTargetStatus(in *config.ConfigSetTargetStatus, out *ConfigSetTargetStatus, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_condition_Condition_To_v1alpha1_Condition(&in.Condition, &out.Condition, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ConfigSetTargetStatus_To_v1alpha1_ConfigSetTargetStatus is an autogenerated conversion function.
func Convert_config_ConfigSetTargetStatus_To_v1alpha1_ConfigSetTargetStatus(in *config.ConfigSetTargetStatus, out *ConfigSetTargetStatus, s conversion.Scope) error {
	return autoConvert_config_ConfigSetTargetStatus_To_v1alpha1_ConfigSetTargetStatus(in, out, s)
}

func autoConvert_v1alpha1_ConfigSpec_To_config_ConfigSpec(in *ConfigSpec, out *config.ConfigSpec, s conversion.Scope) error {
	out.Lifecycle = (*config.Lifecycle)(unsafe.Pointer(in.Lifecycle))
	out.Priority = in.Priority
	out.Revertive = (*bool)(unsafe.Pointer(in.Revertive))
	out.Config = *(*[]config.ConfigBlob)(unsafe.Pointer(&in.Config))
	return nil
}

// Convert_v1alpha1_ConfigSpec_To_config_ConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_ConfigSpec_To_config_ConfigSpec(in *ConfigSpec, out *config.ConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigSpec_To_config_ConfigSpec(in, out, s)
}

func autoConvert_config_ConfigSpec_To_v1alpha1_ConfigSpec(in *config.ConfigSpec, out *ConfigSpec, s conversion.Scope) error {
	out.Lifecycle = (*Lifecycle)(unsafe.Pointer(in.Lifecycle))
	out.Priority = in.Priority
	out.Revertive = (*bool)(unsafe.Pointer(in.Revertive))
	out.Config = *(*[]ConfigBlob)(unsafe.Pointer(&in.Config))
	return nil
}

// Convert_config_ConfigSpec_To_v1alpha1_ConfigSpec is an autogenerated conversion function.
func Convert_config_ConfigSpec_To_v1alpha1_ConfigSpec(in *config.ConfigSpec, out *ConfigSpec, s conversion.Scope) error {
	return autoConvert_config_ConfigSpec_To_v1alpha1_ConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_ConfigStatus_To_config_ConfigStatus(in *ConfigStatus, out *config.ConfigStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ConditionedStatus_To_condition_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	out.LastKnownGoodSchema = (*config.ConfigStatusLastKnownGoodSchema)(unsafe.Pointer(in.LastKnownGoodSchema))
	out.AppliedConfig = (*config.ConfigSpec)(unsafe.Pointer(in.AppliedConfig))
	out.DeviationGeneration = (*int64)(unsafe.Pointer(in.DeviationGeneration))
	return nil
}

// Convert_v1alpha1_ConfigStatus_To_config_ConfigStatus is an autogenerated conversion function.
func Convert_v1alpha1_ConfigStatus_To_config_ConfigStatus(in *ConfigStatus, out *config.ConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigStatus_To_config_ConfigStatus(in, out, s)
}

func autoConvert_config_ConfigStatus_To_v1alpha1_ConfigStatus(in *config.ConfigStatus, out *ConfigStatus, s conversion.Scope) error {
	if err := Convert_condition_ConditionedStatus_To_v1alpha1_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	out.LastKnownGoodSchema = (*ConfigStatusLastKnownGoodSchema)(unsafe.Pointer(in.LastKnownGoodSchema))
	out.AppliedConfig = (*ConfigSpec)(unsafe.Pointer(in.AppliedConfig))
	out.DeviationGeneration = (*int64)(unsafe.Pointer(in.DeviationGeneration))
	return nil
}

// Convert_config_ConfigStatus_To_v1alpha1_ConfigStatus is an autogenerated conversion function.
func Convert_config_ConfigStatus_To_v1alpha1_ConfigStatus(in *config.ConfigStatus, out *ConfigStatus, s conversion.Scope) error {
	return autoConvert_config_ConfigStatus_To_v1alpha1_ConfigStatus(in, out, s)
}

func autoConvert_v1alpha1_ConfigStatusLastKnownGoodSchema_To_config_ConfigStatusLastKnownGoodSchema(in *ConfigStatusLastKnownGoodSchema, out *config.ConfigStatusLastKnownGoodSchema, s conversion.Scope) error {
	out.Type = in.Type
	out.Vendor = in.Vendor
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_ConfigStatusLastKnownGoodSchema_To_config_ConfigStatusLastKnownGoodSchema is an autogenerated conversion function.
func Convert_v1alpha1_ConfigStatusLastKnownGoodSchema_To_config_ConfigStatusLastKnownGoodSchema(in *ConfigStatusLastKnownGoodSchema, out *config.ConfigStatusLastKnownGoodSchema, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigStatusLastKnownGoodSchema_To_config_ConfigStatusLastKnownGoodSchema(in, out, s)
}

func autoConvert_config_ConfigStatusLastKnownGoodSchema_To_v1alpha1_ConfigStatusLastKnownGoodSchema(in *config.ConfigStatusLastKnownGoodSchema, out *ConfigStatusLastKnownGoodSchema, s conversion.Scope) error {
	out.Type = in.Type
	out.Vendor = in.Vendor
	out.Version = in.Version
	return nil
}

// Convert_config_ConfigStatusLastKnownGoodSchema_To_v1alpha1_ConfigStatusLastKnownGoodSchema is an autogenerated conversion function.
func Convert_config_ConfigStatusLastKnownGoodSchema_To_v1alpha1_ConfigStatusLastKnownGoodSchema(in *config.ConfigStatusLastKnownGoodSchema, out *ConfigStatusLastKnownGoodSchema, s conversion.Scope) error {
	return autoConvert_config_ConfigStatusLastKnownGoodSchema_To_v1alpha1_ConfigStatusLastKnownGoodSchema(in, out, s)
}

func autoConvert_v1alpha1_Deviation_To_config_Deviation(in *Deviation, out *config.Deviation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DeviationSpec_To_config_DeviationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeviationStatus_To_config_DeviationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Deviation_To_config_Deviation is an autogenerated conversion function.
func Convert_v1alpha1_Deviation_To_config_Deviation(in *Deviation, out *config.Deviation, s conversion.Scope) error {
	return autoConvert_v1alpha1_Deviation_To_config_Deviation(in, out, s)
}

func autoConvert_config_Deviation_To_v1alpha1_Deviation(in *config.Deviation, out *Deviation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_config_DeviationSpec_To_v1alpha1_DeviationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_config_DeviationStatus_To_v1alpha1_DeviationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Deviation_To_v1alpha1_Deviation is an autogenerated conversion function.
func Convert_config_Deviation_To_v1alpha1_Deviation(in *config.Deviation, out *Deviation, s conversion.Scope) error {
	return autoConvert_config_Deviation_To_v1alpha1_Deviation(in, out, s)
}

func autoConvert_v1alpha1_DeviationList_To_config_DeviationList(in *DeviationList, out *config.DeviationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]config.Deviation, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Deviation_To_config_Deviation(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_DeviationList_To_config_DeviationList is an autogenerated conversion function.
func Convert_v1alpha1_DeviationList_To_config_DeviationList(in *DeviationList, out *config.DeviationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviationList_To_config_DeviationList(in, out, s)
}

func autoConvert_config_DeviationList_To_v1alpha1_DeviationList(in *config.DeviationList, out *DeviationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Deviation, len(*in))
		for i := range *in {
			if err := Convert_config_Deviation_To_v1alpha1_Deviation(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_config_DeviationList_To_v1alpha1_DeviationList is an autogenerated conversion function.
func Convert_config_DeviationList_To_v1alpha1_DeviationList(in *config.DeviationList, out *DeviationList, s conversion.Scope) error {
	return autoConvert_config_DeviationList_To_v1alpha1_DeviationList(in, out, s)
}

func autoConvert_v1alpha1_DeviationSpec_To_config_DeviationSpec(in *DeviationSpec, out *config.DeviationSpec, s conversion.Scope) error {
	out.DeviationType = (*config.DeviationType)(unsafe.Pointer(in.DeviationType))
	out.Deviations = *(*[]config.ConfigDeviation)(unsafe.Pointer(&in.Deviations))
	return nil
}

// Convert_v1alpha1_DeviationSpec_To_config_DeviationSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeviationSpec_To_config_DeviationSpec(in *DeviationSpec, out *config.DeviationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviationSpec_To_config_DeviationSpec(in, out, s)
}

func autoConvert_config_DeviationSpec_To_v1alpha1_DeviationSpec(in *config.DeviationSpec, out *DeviationSpec, s conversion.Scope) error {
	out.DeviationType = (*DeviationType)(unsafe.Pointer(in.DeviationType))
	out.Deviations = *(*[]ConfigDeviation)(unsafe.Pointer(&in.Deviations))
	return nil
}

// Convert_config_DeviationSpec_To_v1alpha1_DeviationSpec is an autogenerated conversion function.
func Convert_config_DeviationSpec_To_v1alpha1_DeviationSpec(in *config.DeviationSpec, out *DeviationSpec, s conversion.Scope) error {
	return autoConvert_config_DeviationSpec_To_v1alpha1_DeviationSpec(in, out, s)
}

func autoConvert_v1alpha1_DeviationStatus_To_config_DeviationStatus(in *DeviationStatus, out *config.DeviationStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ConditionedStatus_To_condition_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DeviationStatus_To_config_DeviationStatus is an autogenerated conversion function.
func Convert_v1alpha1_DeviationStatus_To_config_DeviationStatus(in *DeviationStatus, out *config.DeviationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviationStatus_To_config_DeviationStatus(in, out, s)
}

func autoConvert_config_DeviationStatus_To_v1alpha1_DeviationStatus(in *config.DeviationStatus, out *DeviationStatus, s conversion.Scope) error {
	if err := Convert_condition_ConditionedStatus_To_v1alpha1_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_DeviationStatus_To_v1alpha1_DeviationStatus is an autogenerated conversion function.
func Convert_config_DeviationStatus_To_v1alpha1_DeviationStatus(in *config.DeviationStatus, out *DeviationStatus, s conversion.Scope) error {
	return autoConvert_config_DeviationStatus_To_v1alpha1_DeviationStatus(in, out, s)
}

func autoConvert_v1alpha1_DiscoveryInfo_To_config_DiscoveryInfo(in *DiscoveryInfo, out *config.DiscoveryInfo, s conversion.Scope) error {
	out.Protocol = in.Protocol
	out.Provider = in.Provider
	out.Version = in.Version
	out.Hostname = in.Hostname
	out.Platform = in.Platform
	out.MacAddress = in.MacAddress
	out.SerialNumber = in.SerialNumber
	out.SupportedEncodings = *(*[]string)(unsafe.Pointer(&in.SupportedEncodings))
	return nil
}

// Convert_v1alpha1_DiscoveryInfo_To_config_DiscoveryInfo is an autogenerated conversion function.
func Convert_v1alpha1_DiscoveryInfo_To_config_DiscoveryInfo(in *DiscoveryInfo, out *config.DiscoveryInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiscoveryInfo_To_config_DiscoveryInfo(in, out, s)
}

func autoConvert_config_DiscoveryInfo_To_v1alpha1_DiscoveryInfo(in *config.DiscoveryInfo, out *DiscoveryInfo, s conversion.Scope) error {
	out.Protocol = in.Protocol
	out.Provider = in.Provider
	out.Version = in.Version
	out.Hostname = in.Hostname
	out.Platform = in.Platform
	out.MacAddress = in.MacAddress
	out.SerialNumber = in.SerialNumber
	out.SupportedEncodings = *(*[]string)(unsafe.Pointer(&in.SupportedEncodings))
	return nil
}

// Convert_config_DiscoveryInfo_To_v1alpha1_DiscoveryInfo is an autogenerated conversion function.
func Convert_config_DiscoveryInfo_To_v1alpha1_DiscoveryInfo(in *config.DiscoveryInfo, out *DiscoveryInfo, s conversion.Scope) error {
	return autoConvert_config_DiscoveryInfo_To_v1alpha1_DiscoveryInfo(in, out, s)
}

func autoConvert_v1alpha1_Lifecycle_To_config_Lifecycle(in *Lifecycle, out *config.Lifecycle, s conversion.Scope) error {
	out.DeletionPolicy = config.DeletionPolicy(in.DeletionPolicy)
	return nil
}

// Convert_v1alpha1_Lifecycle_To_config_Lifecycle is an autogenerated conversion function.
func Convert_v1alpha1_Lifecycle_To_config_Lifecycle(in *Lifecycle, out *config.Lifecycle, s conversion.Scope) error {
	return autoConvert_v1alpha1_Lifecycle_To_config_Lifecycle(in, out, s)
}

func autoConvert_config_Lifecycle_To_v1alpha1_Lifecycle(in *config.Lifecycle, out *Lifecycle, s conversion.Scope) error {
	out.DeletionPolicy = DeletionPolicy(in.DeletionPolicy)
	return nil
}

// Convert_config_Lifecycle_To_v1alpha1_Lifecycle is an autogenerated conversion function.
func Convert_config_Lifecycle_To_v1alpha1_Lifecycle(in *config.Lifecycle, out *Lifecycle, s conversion.Scope) error {
	return autoConvert_config_Lifecycle_To_v1alpha1_Lifecycle(in, out, s)
}

func autoConvert_v1alpha1_RunningConfig_To_config_RunningConfig(in *RunningConfig, out *config.RunningConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RunningConfigSpec_To_config_RunningConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RunningConfigStatus_To_config_RunningConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RunningConfig_To_config_RunningConfig is an autogenerated conversion function.
func Convert_v1alpha1_RunningConfig_To_config_RunningConfig(in *RunningConfig, out *config.RunningConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RunningConfig_To_config_RunningConfig(in, out, s)
}

func autoConvert_config_RunningConfig_To_v1alpha1_RunningConfig(in *config.RunningConfig, out *RunningConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_config_RunningConfigSpec_To_v1alpha1_RunningConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_config_RunningConfigStatus_To_v1alpha1_RunningConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_RunningConfig_To_v1alpha1_RunningConfig is an autogenerated conversion function.
func Convert_config_RunningConfig_To_v1alpha1_RunningConfig(in *config.RunningConfig, out *RunningConfig, s conversion.Scope) error {
	return autoConvert_config_RunningConfig_To_v1alpha1_RunningConfig(in, out, s)
}

func autoConvert_v1alpha1_RunningConfigList_To_config_RunningConfigList(in *RunningConfigList, out *config.RunningConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]config.RunningConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RunningConfigList_To_config_RunningConfigList is an autogenerated conversion function.
func Convert_v1alpha1_RunningConfigList_To_config_RunningConfigList(in *RunningConfigList, out *config.RunningConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RunningConfigList_To_config_RunningConfigList(in, out, s)
}

func autoConvert_config_RunningConfigList_To_v1alpha1_RunningConfigList(in *config.RunningConfigList, out *RunningConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RunningConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_config_RunningConfigList_To_v1alpha1_RunningConfigList is an autogenerated conversion function.
func Convert_config_RunningConfigList_To_v1alpha1_RunningConfigList(in *config.RunningConfigList, out *RunningConfigList, s conversion.Scope) error {
	return autoConvert_config_RunningConfigList_To_v1alpha1_RunningConfigList(in, out, s)
}

func autoConvert_v1alpha1_RunningConfigSpec_To_config_RunningConfigSpec(in *RunningConfigSpec, out *config.RunningConfigSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_RunningConfigSpec_To_config_RunningConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_RunningConfigSpec_To_config_RunningConfigSpec(in *RunningConfigSpec, out *config.RunningConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RunningConfigSpec_To_config_RunningConfigSpec(in, out, s)
}

func autoConvert_config_RunningConfigSpec_To_v1alpha1_RunningConfigSpec(in *config.RunningConfigSpec, out *RunningConfigSpec, s conversion.Scope) error {
	return nil
}

// Convert_config_RunningConfigSpec_To_v1alpha1_RunningConfigSpec is an autogenerated conversion function.
func Convert_config_RunningConfigSpec_To_v1alpha1_RunningConfigSpec(in *config.RunningConfigSpec, out *RunningConfigSpec, s conversion.Scope) error {
	return autoConvert_config_RunningConfigSpec_To_v1alpha1_RunningConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_RunningConfigStatus_To_config_RunningConfigStatus(in *RunningConfigStatus, out *config.RunningConfigStatus, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_RunningConfigStatus_To_config_RunningConfigStatus is an autogenerated conversion function.
func Convert_v1alpha1_RunningConfigStatus_To_config_RunningConfigStatus(in *RunningConfigStatus, out *config.RunningConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RunningConfigStatus_To_config_RunningConfigStatus(in, out, s)
}

func autoConvert_config_RunningConfigStatus_To_v1alpha1_RunningConfigStatus(in *config.RunningConfigStatus, out *RunningConfigStatus, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_config_RunningConfigStatus_To_v1alpha1_RunningConfigStatus is an autogenerated conversion function.
func Convert_config_RunningConfigStatus_To_v1alpha1_RunningConfigStatus(in *config.RunningConfigStatus, out *RunningConfigStatus, s conversion.Scope) error {
	return autoConvert_config_RunningConfigStatus_To_v1alpha1_RunningConfigStatus(in, out, s)
}

func autoConvert_v1alpha1_SensitiveConfig_To_config_SensitiveConfig(in *SensitiveConfig, out *config.SensitiveConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SensitiveConfigSpec_To_config_SensitiveConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SensitiveConfigStatus_To_config_SensitiveConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SensitiveConfig_To_config_SensitiveConfig is an autogenerated conversion function.
func Convert_v1alpha1_SensitiveConfig_To_config_SensitiveConfig(in *SensitiveConfig, out *config.SensitiveConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_SensitiveConfig_To_config_SensitiveConfig(in, out, s)
}

func autoConvert_config_SensitiveConfig_To_v1alpha1_SensitiveConfig(in *config.SensitiveConfig, out *SensitiveConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_config_SensitiveConfigSpec_To_v1alpha1_SensitiveConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_config_SensitiveConfigStatus_To_v1alpha1_SensitiveConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_SensitiveConfig_To_v1alpha1_SensitiveConfig is an autogenerated conversion function.
func Convert_config_SensitiveConfig_To_v1alpha1_SensitiveConfig(in *config.SensitiveConfig, out *SensitiveConfig, s conversion.Scope) error {
	return autoConvert_config_SensitiveConfig_To_v1alpha1_SensitiveConfig(in, out, s)
}

func autoConvert_v1alpha1_SensitiveConfigData_To_config_SensitiveConfigData(in *SensitiveConfigData, out *config.SensitiveConfigData, s conversion.Scope) error {
	out.Path = in.Path
	out.SecretKeyRef = in.SecretKeyRef
	return nil
}

// Convert_v1alpha1_SensitiveConfigData_To_config_SensitiveConfigData is an autogenerated conversion function.
func Convert_v1alpha1_SensitiveConfigData_To_config_SensitiveConfigData(in *SensitiveConfigData, out *config.SensitiveConfigData, s conversion.Scope) error {
	return autoConvert_v1alpha1_SensitiveConfigData_To_config_SensitiveConfigData(in, out, s)
}

func autoConvert_config_SensitiveConfigData_To_v1alpha1_SensitiveConfigData(in *config.SensitiveConfigData, out *SensitiveConfigData, s conversion.Scope) error {
	out.Path = in.Path
	out.SecretKeyRef = in.SecretKeyRef
	return nil
}

// Convert_config_SensitiveConfigData_To_v1alpha1_SensitiveConfigData is an autogenerated conversion function.
func Convert_config_SensitiveConfigData_To_v1alpha1_SensitiveConfigData(in *config.SensitiveConfigData, out *SensitiveConfigData, s conversion.Scope) error {
	return autoConvert_config_SensitiveConfigData_To_v1alpha1_SensitiveConfigData(in, out, s)
}

func autoConvert_v1alpha1_SensitiveConfigList_To_config_SensitiveConfigList(in *SensitiveConfigList, out *config.SensitiveConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]config.SensitiveConfig, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_SensitiveConfig_To_config_SensitiveConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_SensitiveConfigList_To_config_SensitiveConfigList is an autogenerated conversion function.
func Convert_v1alpha1_SensitiveConfigList_To_config_SensitiveConfigList(in *SensitiveConfigList, out *config.SensitiveConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SensitiveConfigList_To_config_SensitiveConfigList(in, out, s)
}

func autoConvert_config_SensitiveConfigList_To_v1alpha1_SensitiveConfigList(in *config.SensitiveConfigList, out *SensitiveConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SensitiveConfig, len(*in))
		for i := range *in {
			if err := Convert_config_SensitiveConfig_To_v1alpha1_SensitiveConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_config_SensitiveConfigList_To_v1alpha1_SensitiveConfigList is an autogenerated conversion function.
func Convert_config_SensitiveConfigList_To_v1alpha1_SensitiveConfigList(in *config.SensitiveConfigList, out *SensitiveConfigList, s conversion.Scope) error {
	return autoConvert_config_SensitiveConfigList_To_v1alpha1_SensitiveConfigList(in, out, s)
}

func autoConvert_v1alpha1_SensitiveConfigSpec_To_config_SensitiveConfigSpec(in *SensitiveConfigSpec, out *config.SensitiveConfigSpec, s conversion.Scope) error {
	out.Lifecycle = (*config.Lifecycle)(unsafe.Pointer(in.Lifecycle))
	out.Priority = in.Priority
	out.Revertive = (*bool)(unsafe.Pointer(in.Revertive))
	out.Config = *(*[]config.SensitiveConfigData)(unsafe.Pointer(&in.Config))
	return nil
}

// Convert_v1alpha1_SensitiveConfigSpec_To_config_SensitiveConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_SensitiveConfigSpec_To_config_SensitiveConfigSpec(in *SensitiveConfigSpec, out *config.SensitiveConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SensitiveConfigSpec_To_config_SensitiveConfigSpec(in, out, s)
}

func autoConvert_config_SensitiveConfigSpec_To_v1alpha1_SensitiveConfigSpec(in *config.SensitiveConfigSpec, out *SensitiveConfigSpec, s conversion.Scope) error {
	out.Lifecycle = (*Lifecycle)(unsafe.Pointer(in.Lifecycle))
	out.Priority = in.Priority
	out.Revertive = (*bool)(unsafe.Pointer(in.Revertive))
	out.Config = *(*[]SensitiveConfigData)(unsafe.Pointer(&in.Config))
	return nil
}

// Convert_config_SensitiveConfigSpec_To_v1alpha1_SensitiveConfigSpec is an autogenerated conversion function.
func Convert_config_SensitiveConfigSpec_To_v1alpha1_SensitiveConfigSpec(in *config.SensitiveConfigSpec, out *SensitiveConfigSpec, s conversion.Scope) error {
	return autoConvert_config_SensitiveConfigSpec_To_v1alpha1_SensitiveConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_SensitiveConfigStatus_To_config_SensitiveConfigStatus(in *SensitiveConfigStatus, out *config.SensitiveConfigStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ConditionedStatus_To_condition_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	out.LastKnownGoodSchema = (*config.ConfigStatusLastKnownGoodSchema)(unsafe.Pointer(in.LastKnownGoodSchema))
	out.AppliedSensitiveConfig = (*config.SensitiveConfigSpec)(unsafe.Pointer(in.AppliedSensitiveConfig))
	out.DeviationGeneration = (*int64)(unsafe.Pointer(in.DeviationGeneration))
	return nil
}

// Convert_v1alpha1_SensitiveConfigStatus_To_config_SensitiveConfigStatus is an autogenerated conversion function.
func Convert_v1alpha1_SensitiveConfigStatus_To_config_SensitiveConfigStatus(in *SensitiveConfigStatus, out *config.SensitiveConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SensitiveConfigStatus_To_config_SensitiveConfigStatus(in, out, s)
}

func autoConvert_config_SensitiveConfigStatus_To_v1alpha1_SensitiveConfigStatus(in *config.SensitiveConfigStatus, out *SensitiveConfigStatus, s conversion.Scope) error {
	if err := Convert_condition_ConditionedStatus_To_v1alpha1_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	out.LastKnownGoodSchema = (*ConfigStatusLastKnownGoodSchema)(unsafe.Pointer(in.LastKnownGoodSchema))
	out.AppliedSensitiveConfig = (*SensitiveConfigSpec)(unsafe.Pointer(in.AppliedSensitiveConfig))
	out.DeviationGeneration = (*int64)(unsafe.Pointer(in.DeviationGeneration))
	return nil
}

// Convert_config_SensitiveConfigStatus_To_v1alpha1_SensitiveConfigStatus is an autogenerated conversion function.
func Convert_config_SensitiveConfigStatus_To_v1alpha1_SensitiveConfigStatus(in *config.SensitiveConfigStatus, out *SensitiveConfigStatus, s conversion.Scope) error {
	return autoConvert_config_SensitiveConfigStatus_To_v1alpha1_SensitiveConfigStatus(in, out, s)
}

func autoConvert_v1alpha1_Target_To_config_Target(in *Target, out *config.Target, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TargetSpec_To_config_TargetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TargetStatus_To_config_TargetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Target_To_config_Target is an autogenerated conversion function.
func Convert_v1alpha1_Target_To_config_Target(in *Target, out *config.Target, s conversion.Scope) error {
	return autoConvert_v1alpha1_Target_To_config_Target(in, out, s)
}

func autoConvert_config_Target_To_v1alpha1_Target(in *config.Target, out *Target, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_config_TargetSpec_To_v1alpha1_TargetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_config_TargetStatus_To_v1alpha1_TargetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Target_To_v1alpha1_Target is an autogenerated conversion function.
func Convert_config_Target_To_v1alpha1_Target(in *config.Target, out *Target, s conversion.Scope) error {
	return autoConvert_config_Target_To_v1alpha1_Target(in, out, s)
}

func autoConvert_v1alpha1_TargetList_To_config_TargetList(in *TargetList, out *config.TargetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]config.Target, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Target_To_config_Target(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_TargetList_To_config_TargetList is an autogenerated conversion function.
func Convert_v1alpha1_TargetList_To_config_TargetList(in *TargetList, out *config.TargetList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TargetList_To_config_TargetList(in, out, s)
}

func autoConvert_config_TargetList_To_v1alpha1_TargetList(in *config.TargetList, out *TargetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Target, len(*in))
		for i := range *in {
			if err := Convert_config_Target_To_v1alpha1_Target(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_config_TargetList_To_v1alpha1_TargetList is an autogenerated conversion function.
func Convert_config_TargetList_To_v1alpha1_TargetList(in *config.TargetList, out *TargetList, s conversion.Scope) error {
	return autoConvert_config_TargetList_To_v1alpha1_TargetList(in, out, s)
}

func autoConvert_v1alpha1_TargetSpec_To_config_TargetSpec(in *TargetSpec, out *config.TargetSpec, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Address = in.Address
	out.TargetProfile = in.TargetProfile
	return nil
}

// Convert_v1alpha1_TargetSpec_To_config_TargetSpec is an autogenerated conversion function.
func Convert_v1alpha1_TargetSpec_To_config_TargetSpec(in *TargetSpec, out *config.TargetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TargetSpec_To_config_TargetSpec(in, out, s)
}

func autoConvert_config_TargetSpec_To_v1alpha1_TargetSpec(in *config.TargetSpec, out *TargetSpec, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Address = in.Address
	out.TargetProfile = in.TargetProfile
	return nil
}

// Convert_config_TargetSpec_To_v1alpha1_TargetSpec is an autogenerated conversion function.
func Convert_config_TargetSpec_To_v1alpha1_TargetSpec(in *config.TargetSpec, out *TargetSpec, s conversion.Scope) error {
	return autoConvert_config_TargetSpec_To_v1alpha1_TargetSpec(in, out, s)
}

func autoConvert_v1alpha1_TargetStatus_To_config_TargetStatus(in *TargetStatus, out *config.TargetStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ConditionedStatus_To_condition_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	out.DiscoveryInfo = (*config.DiscoveryInfo)(unsafe.Pointer(in.DiscoveryInfo))
	out.UsedReferences = (*config.TargetStatusUsedReferences)(unsafe.Pointer(in.UsedReferences))
	return nil
}

// Convert_v1alpha1_TargetStatus_To_config_TargetStatus is an autogenerated conversion function.
func Convert_v1alpha1_TargetStatus_To_config_TargetStatus(in *TargetStatus, out *config.TargetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_TargetStatus_To_config_TargetStatus(in, out, s)
}

func autoConvert_config_TargetStatus_To_v1alpha1_TargetStatus(in *config.TargetStatus, out *TargetStatus, s conversion.Scope) error {
	if err := Convert_condition_ConditionedStatus_To_v1alpha1_ConditionedStatus(&in.ConditionedStatus, &out.ConditionedStatus, s); err != nil {
		return err
	}
	out.DiscoveryInfo = (*DiscoveryInfo)(unsafe.Pointer(in.DiscoveryInfo))
	out.UsedReferences = (*TargetStatusUsedReferences)(unsafe.Pointer(in.UsedReferences))
	return nil
}

// Convert_config_TargetStatus_To_v1alpha1_TargetStatus is an autogenerated conversion function.
func Convert_config_TargetStatus_To_v1alpha1_TargetStatus(in *config.TargetStatus, out *TargetStatus, s conversion.Scope) error {
	return autoConvert_config_TargetStatus_To_v1alpha1_TargetStatus(in, out, s)
}

func autoConvert_v1alpha1_TargetStatusUsedReferences_To_config_TargetStatusUsedReferences(in *TargetStatusUsedReferences, out *config.TargetStatusUsedReferences, s conversion.Scope) error {
	out.SecretResourceVersion = in.SecretResourceVersion
	out.TLSSecretResourceVersion = in.TLSSecretResourceVersion
	out.ConnectionProfileResourceVersion = in.ConnectionProfileResourceVersion
	out.SyncProfileResourceVersion = in.SyncProfileResourceVersion
	return nil
}

// Convert_v1alpha1_TargetStatusUsedReferences_To_config_TargetStatusUsedReferences is an autogenerated conversion function.
func Convert_v1alpha1_TargetStatusUsedReferences_To_config_TargetStatusUsedReferences(in *TargetStatusUsedReferences, out *config.TargetStatusUsedReferences, s conversion.Scope) error {
	return autoConvert_v1alpha1_TargetStatusUsedReferences_To_config_TargetStatusUsedReferences(in, out, s)
}

func autoConvert_config_TargetStatusUsedReferences_To_v1alpha1_TargetStatusUsedReferences(in *config.TargetStatusUsedReferences, out *TargetStatusUsedReferences, s conversion.Scope) error {
	out.SecretResourceVersion = in.SecretResourceVersion
	out.TLSSecretResourceVersion = in.TLSSecretResourceVersion
	out.ConnectionProfileResourceVersion = in.ConnectionProfileResourceVersion
	out.SyncProfileResourceVersion = in.SyncProfileResourceVersion
	return nil
}

// Convert_config_TargetStatusUsedReferences_To_v1alpha1_TargetStatusUsedReferences is an autogenerated conversion function.
func Convert_config_TargetStatusUsedReferences_To_v1alpha1_TargetStatusUsedReferences(in *config.TargetStatusUsedReferences, out *TargetStatusUsedReferences, s conversion.Scope) error {
	return autoConvert_config_TargetStatusUsedReferences_To_v1alpha1_TargetStatusUsedReferences(in, out, s)
}
