apiVersion: v1
kind: ConfigMap
metadata:
  name: context
data: 
  sdcApiServerImage: ghcr.io/sdcio/config-server-api-server:latest
  sdcControllerImage: ghcr.io/sdcio/config-server-controller:latest
  dataServerImage: ghcr.io/sdcio/data-server:latest

