apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdc-controller-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sdc-controller-clusterrole
subjects:
- kind: ServiceAccount
  name: sdc-controller
  namespace: sdc-system