apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdc-controller-metrics-auth-role
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["subjectaccessreviews.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
