apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sdc-controller-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: sdc-controller
  namespace: sdc-system
