apiVersion: v1
kind: Service
metadata:
  name: sdc-controller-server-metrics
  namespace: sdc-system
  labels:
    app.kubernetes.io/name: sdc-controller
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: sdc-controller
