apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: sdc-system
  labels:
    app.kubernetes.io/name: sdc-api-server
spec:
  ports:
  - name: api-service
    port: 6443
    targetPort: api-service
  selector:
    app.kubernetes.io/name: sdc-api-server
