apiVersion: v1
kind: Service
metadata:
  name: sdc-controller-target-metrics
  namespace: sdc-system
  labels:
    app.kubernetes.io/name: sdc-controller
spec:
  ports:
  - name: targetmetrics
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: sdc-controller
